"""
Script plots success rate over generations for the GA strategy. 

It reads the CSV generated by the GA strategy and creates a line graph showing how the percentage of successful robots evolves across generations. The graph is saved in the same output folder as "success_trend.png".
"""
import pandas as pd
import matplotlib.pyplot as plt
import os
import argparse

def plot_success_rate(output_folder):
    """
    Plots the success rate of the GA strategy over generations.
    Args:
        output_folder (str): Path to the timestamped output folder containing the CSV file.
    """
    # Path to the CSV generated by the GA strategy
    csv_path = os.path.join(output_folder, "generation_results.csv")
    
    if not os.path.exists(csv_path):
        print(f"Error: Could not find {csv_path}")
        return

    # Load the data
    # Note: We strip '%' from the column if it's stored as a string
    df = pd.read_csv(csv_path)
    
    # Ensure the success column is numeric
    column_name = "% of Generation Successful"
    df[column_name] = df[column_name].astype(str).str.replace('%', '').astype(float)

    # Plotting
    plt.figure(figsize=(10, 6))
    plt.plot(df['Generation'], df[column_name], marker='o', linestyle='-', color='green')
    
    plt.title(f"Evolution Progress: {os.path.basename(output_folder)}")
    plt.xlabel("Generation")
    plt.ylabel("Success Rate (%)")
    plt.grid(True, linestyle='--', alpha=0.7)
    # plt.ylim(0, 105)  # Success is 0-100%
    
    # Save the graph to the output folder
    graph_path = os.path.join(output_folder, "success_trend.png")
    plt.savefig(graph_path)
    plt.show()
    
    print(f"Graph saved to: {graph_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("folder", help="Path to the timestamped output folder", default="output/2026-03-23-151514_ga")
    args = parser.parse_args()
    
    plot_success_rate(args.folder)